### ISSUE TITLE
Custom person Image

### ISSUE THREAD

**Issue by Abdullahkhan5** [lastdefiance20/TryYours-Virtual-Try-On#3]
Does this works with the custom data as well?

**Comment by lastdefiance20** [comment]
If you were talking about using custom data that contains clothes and person images for Inference, I think it generates well even though there is some issue to solve like as background artifact.

you can always try your custom data at [colab](https://colab.research.google.com/drive/1fP5Wia4ukTp6WC5FlSa7InW7cOLXCePy?usp=sharing)

**Comment by stevemartinov** [comment]
@lastdefiance20 Hi, given I have two input images (person and cloth), do you have instructions on how to run the code?

**Comment by lastdefiance20** [comment]
@stevemartinov Hi, instructions are written at the colab. If you want to run the code locally, you need to use the docker image informed in "README.md", and follow all "Setup" / "Download Pre-trained Models" parts written at the colab before generating images.

After then, just replace the static/cloth_web.jpg file to your custom clothes .jpg file, and replace the static/origin_web.jpg file to your custom person .jpg file. You can generate the image running main.py. The generated image will be saved as static/finalimg.png

**Comment by Abdullahkhan5** [comment]
Thanks for the help.
I have successfully launched in on colab using my own custom dataset
