### ISSUE TITLE
Openpose installation issues on colab

### ISSUE THREAD

**Issue by Abdullahkhan5** [lastdefiance20/TryYours-Virtual-Try-On#4]
Can you please share your environments details for CUDA, cuDNN versions because openpose does not seem to install on colab 
and giving errors like these https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1322

**Comment by lastdefiance20** [comment]
@Abdullahkhan5 
Could you let me know if you followed all instructions at the colab to generate an image? you don't need to install any other libraries that are not written on colab.

And we don't use the Openpose library. In our code, we use the "Posenet" model to generate a pose estimation and transpose it to the Openpose type.

our environment is based on a docker image (also informed in README.md)

https://hub.docker.com/r/paperspace/gradient-base
docker tag
pt112-tf29-jax0314-py39-20220803

CUDA : 11.2.1 / cuDNN 8.1.1
