### ISSUE TITLE
This model cannot be found, why?https://colab.research.google.com/drive/1fP5Wia4ukTp6WC5FlSa7InW7cOLXCePy?usp=sharing#scrollTo=gJUHNGLorsAR

### ISSUE THREAD

**Issue by xuboot** [lastdefiance20/TryYours-Virtual-Try-On#5]
https://colab.research.google.com/drive/1fP5Wia4ukTp6WC5FlSa7InW7cOLXCePy?usp=sharing#scrollTo=gJUHNGLorsAR

**Comment by lastdefiance20** [comment]
@xuboot I check the original author of HR-VITON has changed the GAN model checkpoint link, so I fixed the broken link in colab. It will work fine from now on!
