### ISSUE TITLE
where is the inference.pth?

### ISSUE THREAD

**Issue by blt232018** [lastdefiance20/TryYours-Virtual-Try-On#8]
![image](https://github.com/lastdefiance20/TryYours-Virtual-Try-On/assets/43393471/5c8d2092-8eb9-40e9-9e0c-5331e334bc92)

Hi bro! In the part of  `Generate semantic segmentation using Graphonomy-Master library` of "main.py", there is a model path named `inference.pth`, but i don't know how to get it or generate it, would you please tell me some infomations about it? thanks

**Comment by lastdefiance20** [comment]
@blt232018 
Hi, thanks for your interest in our project

In the Google colab instruction, '2. Download Pre-trained Models', you can see how to download the inference.pth inside the Graphonomy-master folder.

Or, you can download it using this link [inference.pth](https://drive.google.com/u/0/uc?id=1eUe18HoH05p0yFUd_sN6GXdTj82aW0m9&export=download)

**Comment by blt232018** [comment]
> @blt232018 Hi, thanks for your interest in our project
> 
> In the Google colab instruction, '2. Download Pre-trained Models', you can see how to download the inference.pth inside the Graphonomy-master folder.
> 
> Or, you can download it using this link [inference.pth](https://drive.google.com/u/0/uc?id=1eUe18HoH05p0yFUd_sN6GXdTj82aW0m9&export=download)

@lastdefiance20
thanks for your help very much!!!
I am trying to deploy this project locally. Now I can move on to the next step.

**Comment by blt232018** [comment]
> @blt232018 Hi, thanks for your interest in our project
> 
> In the Google colab instruction, '2. Download Pre-trained Models', you can see how to download the inference.pth inside the Graphonomy-master folder.
> 
> Or, you can download it using this link [inference.pth](https://drive.google.com/u/0/uc?id=1eUe18HoH05p0yFUd_sN6GXdTj82aW0m9&export=download)

@lastdefiance20
thanks for your help very much!!!
I am trying to deploy this project locally. Now I can move on to the next step.
