### ISSUE TITLE
demo UI

### ISSUE THREAD

**Issue by nazapip** [lastdefiance20/TryYours-Virtual-Try-On#9]
Hi,
This is amazing!!.. Its working superb with different images i tried. Now, Can i get any guidance on how can i make a demo UI such as gradio application or streamlit application with this on VS code. Or what essential changes will i have to make in the code files for it?

**Comment by lastdefiance20** [comment]
Hi @nazapip, you can basically just follow the "main.py" file to see over the process of making generated images.
Also, In google colab notebook, you can see where is the place (file path) to put the input person and clothes image.
I believe that you can make your gradio / streamlit application successfully just following colab instructions and code.
